export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_SERVERS_LIST_SUCCESS = 'GET_SERVERS_LIST_SUCCESS';
export const GET_SERVERS_LIST_FAILURE = 'GET_SERVERS_LIST_FAILURE';
